name = "idk123idk123dasa"
main = "src/worker.js"
compatibility_date = "2025-01-01"

# Serve all static files from the project root
[assets]
directory = "./"
not_found_handling = "single-page-application"
